"""Generate a fresh EVM wallet for testnet use and store the key in .env.

Usage: python scripts/new_wallet.py
Then fund the printed address with test ETH (e.g. Sepolia faucet) and set RPC_URL.
"""
from __future__ import annotations

from pathlib import Path

from eth_account import Account

ROOT = Path(__file__).resolve().parent.parent
ENV = ROOT / ".env"


def main() -> None:
    existing = ENV.read_text(encoding="utf-8") if ENV.exists() else ""
    for line in existing.splitlines():
        if line.startswith("PRIVATE_KEY=") and len(line.split("=", 1)[1].strip()) >= 64:
            acct = Account.from_key(line.split("=", 1)[1].strip())
            print(f".env already has a PRIVATE_KEY -> address {acct.address}")
            return
    acct = Account.create()
    with ENV.open("a", encoding="utf-8") as fh:
        fh.write(f"\n# generated by scripts/new_wallet.py - TESTNET ONLY, never fund with real money\nPRIVATE_KEY={acct.key.hex()}\n")
    print(f"new wallet address: {acct.address}")
    print(f"private key saved to {ENV} (gitignored)")
    print("fund it with Sepolia test ETH, e.g. https://cloud.google.com/application/web3/faucet/ethereum/sepolia")


if __name__ == "__main__":
    main()
